<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,2,1,'6Iu55p6c6LWa6ZKx');
$cfg_Cs[2]=array(0,2,1,'5a6J5Y2T6LWa6ZKx');
$cfg_Cs[3]=array(0,2,1,'5omL5py66LWa6ZKx');
$cfg_Cs[4]=array(0,2,1,'57u85ZCI6LWa6ZKx');
$cfg_Cs[5]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[6]=array(5,1,1,'572R56uZ5YWs5ZGK');
$cfg_Cs[7]=array(5,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[8]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[9]=array(8,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[10]=array(8,1,1,'5bm/5ZGK5ZCI5L2c');
$cfg_Cs[11]=array(0,1,1,'5bm754Gv54mH566h55CG');
?>