<li>
              <figure class="icon"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]"/></a></figure>
              <div class="info">
                <h4><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h4>
                <p>[field:description function="cn_substr(@me,120)"/]...</p>
                <p class="appbtn"><a href="[field:arcurl/]" title="[field:title/]">下载</a></p>
              </div>
            </li>