<li>
              <figure class="icon"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]"/></a></figure>
              <div class="info">
                <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
                <div class="meta">人气： <script src="/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]" type='text/javascript' language="javascript"></script> </div>
              </div>
            </li>