<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/210203/1-210203004956.png ",93,240);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/210203/1-210203004956.png";
$z[1][4]['text']="";
$z[1][4]['width']="320";
$z[1][4]['height']="568";
$z[2]=Array("img"," /uploads/allimg/210203/1-210203005000.png ",242,389);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/210203/1-210203005000.png";
$z[2][4]['text']="";
$z[2][4]['width']="320";
$z[2][4]['height']="568";
$z[3]=Array("img"," /uploads/allimg/210203/1-210203005002.png ",391,538);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/210203/1-210203005002.png";
$z[3][4]['text']="";
$z[3][4]['width']="320";
$z[3][4]['height']="568";
$z[4]=Array("img"," /uploads/allimg/210203/1-210203005004.png ",540,687);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/210203/1-210203005004.png";
$z[4][4]['text']="";
$z[4][4]['width']="320";
$z[4][4]['height']="568";

?>