<article class="newsitem">
          <div class="pic"><a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" alt="[field:title/]"></a></div>
          <div class="info">
            <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
            <div class="excerpt">[field:description function="cn_substr(@me,180)"/]...</div>
            <div class="meta"> <span>日期：
              <time>[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
              </span> <span>栏目：<a href="" target="_blank">[field:typename /]</a></span><span>阅读：<script src="/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]" type='text/javascript' language="javascript"></script></span></div>
          </div>
        </article>