<article class="appitem">
          <figure class="icon"> <a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" alt="[field:title/]"/></a> </figure>
          <div class="info">
            <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
            <div class="meta"><span>大小：[field:dx/]</span><span>人气：<script src="/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]" type='text/javascript' language="javascript"></script></span></div>
            <div class="intro">[field:description function="cn_substr(@me,200)"/]...</div>
            <div class="appbtn"> <a href="[field:arcurl/]" title="[field:title/]">下载</a> </div>
          </div>
        </article>