
  <m:item name='幻灯片管理' link='ppt_main.php' rank='c_List' target='main'/>
  <m:item name='广告位管理' link='ad_main.php' rank='c_List' target='main'/>
  <m:item name='自定义表单' link='diy_main.php' rank='c_List' target='main'/>
  <m:item name='默认模板管理' link='templets_main.php' rank='c_List' target='main'/>
  <m:item name='内容模型管理' link='mychannel_main.php' rank='c_List' target='main'/>
  <m:item name='搜索关键词维护' link='search_keywords_main.php' rank='c_List' target='main'/>
  <m:item name='文档关键词维护' link='article_keywords_main.php' rank='sys_Keyword' target='main' />
  <m:item name='重复文档检测' link='article_test_same.php' rank='sys_ArcBatch' target='main' />
